"""extend catalogue commerce inventory models

Revision ID: 44712dfb65f1
Revises: b457d693ff1b
Create Date: 2026-07-04 03:02:22.906249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '44712dfb65f1'
down_revision: Union[str, None] = 'b457d693ff1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_slug'), 'brands', ['slug'], unique=True)
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('discount_type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('min_order', sa.Integer(), nullable=False),
    sa.Column('max_discount', sa.Integer(), nullable=True),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('gst_amount', sa.Integer(), nullable=False),
    sa.Column('delivery_charge', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_number'), 'invoices', ['number'], unique=True)
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('gst_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(length=80), nullable=True),
    sa.Column('refund_amount', sa.Integer(), nullable=False),
    sa.Column('refund_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_order_id'), 'payments', ['order_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_table('inventory_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('change', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_logs_product_id'), 'inventory_logs', ['product_id'], unique=False)
    # NOT NULL columns added to existing tables get a temporary server_default so
    # the already-present rows backfill; the default is dropped at the end of
    # upgrade() so the DB schema matches the (python-default-only) models.
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('enquiries', sa.Column('product_ids', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('enquiries', sa.Column('budget', sa.String(length=60), nullable=True))
    op.add_column('enquiries', sa.Column('source', sa.String(length=30), nullable=False, server_default='website'))
    op.add_column('enquiries', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('enquiries', sa.Column('reply', sa.Text(), nullable=True))
    op.add_column('enquiries', sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('enquiries', sa.Column('followups', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.create_index(op.f('ix_enquiries_archived'), 'enquiries', ['archived'], unique=False)
    op.create_index(op.f('ix_enquiries_assignee_id'), 'enquiries', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_enquiries_status'), 'enquiries', ['status'], unique=False)
    op.create_foreign_key(None, 'enquiries', 'users', ['assignee_id'], ['id'])
    op.add_column('orders', sa.Column('city', sa.String(length=80), nullable=True))
    op.add_column('orders', sa.Column('state', sa.String(length=80), nullable=True))
    op.add_column('orders', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('orders', sa.Column('subtotal', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('gst_amount', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('delivery_charge', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('discount', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('orders', sa.Column('coupon_code', sa.String(length=40), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(length=30), nullable=True))
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=80), nullable=True))
    op.add_column('orders', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_idempotency_key'), 'orders', ['idempotency_key'], unique=True)
    op.create_foreign_key(None, 'orders', 'invoices', ['invoice_id'], ['id'])
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('summary', sa.String(length=400), nullable=True))
    op.add_column('products', sa.Column('benefits', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('products', sa.Column('suitable_surfaces', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('products', sa.Column('uses', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('products', sa.Column('coverage', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('finish', sa.String(length=60), nullable=True))
    op.add_column('products', sa.Column('drying_time', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('application_method', sa.String(length=120), nullable=True))
    op.add_column('products', sa.Column('coats', sa.String(length=40), nullable=True))
    op.add_column('products', sa.Column('pack_sizes', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('products', sa.Column('interior_exterior', sa.String(length=20), nullable=True))
    op.add_column('products', sa.Column('tech_specs', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('products', sa.Column('faqs', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('products', sa.Column('maintenance', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('safety_tips', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('images', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('products', sa.Column('recommended_primer_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('recommended_putty_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('related_product_ids', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('products', sa.Column('seo_title', sa.String(length=160), nullable=True))
    op.add_column('products', sa.Column('seo_description', sa.String(length=320), nullable=True))
    op.add_column('products', sa.Column('sku', sa.String(length=60), nullable=True))
    op.add_column('products', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('products', sa.Column('reserved', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('products', sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_is_featured'), 'products', ['is_featured'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_foreign_key(None, 'products', 'products', ['recommended_putty_id'], ['id'])
    op.create_foreign_key(None, 'products', 'brands', ['brand_id'], ['id'])
    op.create_foreign_key(None, 'products', 'products', ['recommended_primer_id'], ['id'])
    op.add_column('surveys', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('surveys', sa.Column('preferred_time', sa.String(length=40), nullable=True))
    op.add_column('surveys', sa.Column('reference_images', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('surveys', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.add_column('surveys', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_surveys_assignee_id'), 'surveys', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_surveys_status'), 'surveys', ['status'], unique=False)
    op.create_foreign_key(None, 'surveys', 'users', ['assignee_id'], ['id'])
    op.add_column('users', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('addresses', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))

    # Migrate legacy survey status default ("new") to the new lifecycle start.
    op.execute("UPDATE surveys SET status = 'pending' WHERE status = 'new'")

    # Drop the temporary server defaults now that existing rows are backfilled,
    # leaving the columns NOT NULL with app-side (python) defaults only.
    for _table, _col in [
        ("categories", "is_active"),
        ("enquiries", "product_ids"), ("enquiries", "source"),
        ("enquiries", "archived"), ("enquiries", "followups"),
        ("orders", "gst_amount"), ("orders", "delivery_charge"), ("orders", "discount"),
        ("products", "benefits"), ("products", "suitable_surfaces"), ("products", "uses"),
        ("products", "pack_sizes"), ("products", "tech_specs"), ("products", "faqs"),
        ("products", "images"), ("products", "related_product_ids"),
        ("products", "stock"), ("products", "reserved"), ("products", "low_stock_threshold"),
        ("products", "is_active"), ("products", "is_featured"),
        ("surveys", "reference_images"),
        ("users", "addresses"),
    ]:
        op.alter_column(_table, _col, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'addresses')
    op.drop_column('users', 'notes')
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_index(op.f('ix_surveys_status'), table_name='surveys')
    op.drop_index(op.f('ix_surveys_assignee_id'), table_name='surveys')
    op.drop_column('surveys', 'scheduled_at')
    op.drop_column('surveys', 'assignee_id')
    op.drop_column('surveys', 'reference_images')
    op.drop_column('surveys', 'preferred_time')
    op.drop_column('surveys', 'email')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_is_featured'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_column('products', 'is_featured')
    op.drop_column('products', 'is_active')
    op.drop_column('products', 'low_stock_threshold')
    op.drop_column('products', 'reserved')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'price')
    op.drop_column('products', 'sku')
    op.drop_column('products', 'seo_description')
    op.drop_column('products', 'seo_title')
    op.drop_column('products', 'related_product_ids')
    op.drop_column('products', 'recommended_putty_id')
    op.drop_column('products', 'recommended_primer_id')
    op.drop_column('products', 'images')
    op.drop_column('products', 'safety_tips')
    op.drop_column('products', 'maintenance')
    op.drop_column('products', 'faqs')
    op.drop_column('products', 'tech_specs')
    op.drop_column('products', 'interior_exterior')
    op.drop_column('products', 'pack_sizes')
    op.drop_column('products', 'coats')
    op.drop_column('products', 'application_method')
    op.drop_column('products', 'drying_time')
    op.drop_column('products', 'finish')
    op.drop_column('products', 'coverage')
    op.drop_column('products', 'uses')
    op.drop_column('products', 'suitable_surfaces')
    op.drop_column('products', 'benefits')
    op.drop_column('products', 'summary')
    op.drop_column('products', 'brand_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_idempotency_key'), table_name='orders')
    op.drop_column('orders', 'invoice_id')
    op.drop_column('orders', 'idempotency_key')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'coupon_code')
    op.drop_column('orders', 'discount')
    op.drop_column('orders', 'delivery_charge')
    op.drop_column('orders', 'gst_amount')
    op.drop_column('orders', 'subtotal')
    op.drop_column('orders', 'pincode')
    op.drop_column('orders', 'state')
    op.drop_column('orders', 'city')
    op.drop_constraint(None, 'enquiries', type_='foreignkey')
    op.drop_index(op.f('ix_enquiries_status'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_assignee_id'), table_name='enquiries')
    op.drop_index(op.f('ix_enquiries_archived'), table_name='enquiries')
    op.drop_column('enquiries', 'followups')
    op.drop_column('enquiries', 'archived')
    op.drop_column('enquiries', 'reply')
    op.drop_column('enquiries', 'assignee_id')
    op.drop_column('enquiries', 'source')
    op.drop_column('enquiries', 'budget')
    op.drop_column('enquiries', 'product_ids')
    op.drop_column('categories', 'is_active')
    op.drop_index(op.f('ix_inventory_logs_product_id'), table_name='inventory_logs')
    op.drop_table('inventory_logs')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_order_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_number'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.drop_table('coupons')
    op.drop_index(op.f('ix_brands_slug'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
