"""whatsapp messages and leads

Revision ID: 7d3500b99b25
Revises: 44712dfb65f1
Create Date: 2026-07-04 03:42:58.447546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7d3500b99b25'
down_revision: Union[str, None] = '44712dfb65f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wa_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('intent', sa.String(length=40), nullable=True),
    sa.Column('budget', sa.String(length=60), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wa_leads_phone'), 'wa_leads', ['phone'], unique=True)
    op.create_index(op.f('ix_wa_leads_status'), 'wa_leads', ['status'], unique=False)
    op.create_table('wa_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=3), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=40), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wa_messages_phone'), 'wa_messages', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wa_messages_phone'), table_name='wa_messages')
    op.drop_table('wa_messages')
    op.drop_index(op.f('ix_wa_leads_status'), table_name='wa_leads')
    op.drop_index(op.f('ix_wa_leads_phone'), table_name='wa_leads')
    op.drop_table('wa_leads')
    # ### end Alembic commands ###
