"""add product variants and order item variant_label

Revision ID: 8a9f08556507
Revises: a5f6dc36692e
Create Date: 2026-07-03 02:29:28.182306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8a9f08556507'
down_revision: Union[str, None] = 'a5f6dc36692e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('variant_label', sa.String(length=40), nullable=True))
    # Add with a server default so existing rows backfill to an empty list, then
    # drop the default (the app supplies variants explicitly).
    op.add_column(
        'products',
        sa.Column('variants', sa.JSON(), nullable=False, server_default='[]'),
    )
    op.alter_column('products', 'variants', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'variants')
    op.drop_column('order_items', 'variant_label')
    # ### end Alembic commands ###
