"""add user profile fields and user links

Revision ID: b457d693ff1b
Revises: 8a9f08556507
Create Date: 2026-07-03 15:13:24.844188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b457d693ff1b'
down_revision: Union[str, None] = '8a9f08556507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enquiries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_enquiries_user_id'), 'enquiries', ['user_id'], unique=False)
    op.create_foreign_key('fk_enquiries_user_id_users', 'enquiries', 'users', ['user_id'], ['id'])
    op.add_column('orders', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_foreign_key('fk_orders_user_id_users', 'orders', 'users', ['user_id'], ['id'])
    op.add_column('surveys', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_surveys_user_id'), 'surveys', ['user_id'], unique=False)
    op.create_foreign_key('fk_surveys_user_id_users', 'surveys', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('full_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    op.drop_constraint('fk_surveys_user_id_users', 'surveys', type_='foreignkey')
    op.drop_index(op.f('ix_surveys_user_id'), table_name='surveys')
    op.drop_column('surveys', 'user_id')
    op.drop_constraint('fk_orders_user_id_users', 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_column('orders', 'user_id')
    op.drop_constraint('fk_enquiries_user_id_users', 'enquiries', type_='foreignkey')
    op.drop_index(op.f('ix_enquiries_user_id'), table_name='enquiries')
    op.drop_column('enquiries', 'user_id')
    # ### end Alembic commands ###
